library(dplyr)
top3 = spearman = matrix(nrow=10, ncol=3)
colnames(top3) = colnames(spearman) = c('sbv', 'emsbe', 'wis')
for (i in 1:10) {
  metrics = read.csv(paste('allMetrics_run_seed=', 41+i, '.csv', sep=''))
  best = metrics %>% arrange(-returns) %>% head(3) %>% select(returns) %>% unlist() %>% mean()
  worst = metrics %>% arrange(returns) %>% head(3) %>% select(returns) %>% unlist() %>% mean()
  standardize = function(x) (x-worst)/(best-worst)
  top3[i,'sbv'] = metrics %>% arrange(sbv) %>% head(3) %>% select(returns) %>% unlist() %>% mean() %>% standardize()
  spearman[i,'sbv'] = cor(metrics$sbv, metrics$returns, method='spearman')
   top3[i,'emsbe'] = metrics %>% arrange(emsbe_val) %>% head(3) %>% select(returns) %>% unlist() %>% mean() %>% standardize()
   spearman[i,'emsbe'] = cor(metrics$emsbe_val, metrics$returns, method='spearman')
   top3[i,'wis'] = metrics %>% arrange(-wis) %>% head(3) %>% select(returns) %>% unlist() %>% mean() %>% standardize()
   spearman[i,'wis'] = cor(metrics$wis, metrics$returns, method='spearman')
}

print('top-3 policy value (mean)')
colMeans(top3)
print('top-3 policy value (sd)')
apply(top3, 2, sd)
print('spearman (mean)')
colMeans(spearman)
print('spearman (sd)')
apply(spearman, 2, sd)
